# Generated by Django 5.0.6 on 2025-07-11 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_add_prefijo_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedore',
            name='telefono',
            field=models.CharField(help_text='Número de teléfono sin prefijo', max_length=20),
        ),
    ]
