# Generated by Django 5.0.6 on 2025-07-11 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_proveedore_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'No entregado'), ('ENTREGADO', 'Entregado'), ('ANULADA', 'Anulada')], default='PENDIENTE', max_length=30),
        ),
    ]
