# Generated by Django 5.0.6 on 2025-11-27 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_add_categorias_manytomany'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='usuario_confirmo_entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras_confirmadas', to='usuario.usuario'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras_realizadas', to='usuario.usuario'),
        ),
    ]
