# Generated by Django 5.0.6 on 2025-12-07 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_compra_usuario_confirmo_entrega_alter_compra_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionboleta',
            name='direccion',
            field=models.CharField(default='Dirección del negocio', max_length=200),
        ),
        migrations.AlterField(
            model_name='configuracionboleta',
            name='fono',
            field=models.CharField(default='Teléfono de contacto', max_length=50),
        ),
        migrations.AlterField(
            model_name='configuracionboleta',
            name='nombre',
            field=models.CharField(default='Mi Negocio', max_length=100),
        ),
        migrations.AlterField(
            model_name='configuracionboleta',
            name='rut',
            field=models.CharField(default='RUT/NIT: 00.000.000-0', max_length=20),
        ),
    ]
