# Generated by Django 5.0.6 on 2025-12-07 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_configuracionboleta_direccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id_sucursal', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('TIENDA', 'Tienda'), ('BODEGA', 'Bodega')], default='TIENDA', help_text='Tipo de sucursal: Tienda o Bodega', max_length=20)),
                ('correo', models.EmailField(blank=True, null=True)),
                ('prefijo_telefono', models.CharField(default='+56', help_text='Prefijo del país (ej: +56, +1, +34)', max_length=10)),
                ('telefono', models.CharField(blank=True, help_text='Número de teléfono sin prefijo', max_length=20, null=True)),
                ('direccion', models.CharField(max_length=200)),
                ('pais', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('comuna', models.CharField(max_length=50)),
                ('eliminado', models.BooleanField(default=False)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
