# Generated by Django 5.0.6 on 2025-12-07 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_sucursal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sucursal',
            options={'verbose_name': 'Sucursal', 'verbose_name_plural': 'Sucursales'},
        ),
    ]
