# Generated by Django 5.0.6 on 2025-12-08 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_sucursal_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='bodega_salida',
            field=models.ForeignKey(blank=True, help_text='Bodega de donde sale el producto', limit_choices_to={'tipo': 'BODEGA'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_salida', to='home.sucursal'),
        ),
        migrations.AddField(
            model_name='venta',
            name='tienda_llegada',
            field=models.ForeignKey(blank=True, help_text='Tienda donde llega el producto', limit_choices_to={'tipo': 'TIENDA'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_llegada', to='home.sucursal'),
        ),
    ]
