# Generated by Django 5.0.6 on 2025-12-08 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_venta_fecha_entrega_venta_usuario_confirmo_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'No entregado'), ('ENTREGADO', 'Entregado'), ('ANULADA', 'Anulada')], default='PENDIENTE', max_length=30),
        ),
    ]
